name: 06-Matrix-Testing
on: [push]

jobs:
  test-grid:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20, 22]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Tests
        run: echo "Testing on ${{ matrix.os }} with Node ${{ matrix.node-version }}"
